baseURL = "http://limin.me"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hyde-hyde"


[params.social]
    github = "<hanlimin>"
    instagram = "<username>"
    xing = "<username>"
    linkedin = "<username>"
    twitter = "<username>"
    facebook = "<username>"
    microblog = "<username>"
    stackoverflow = "<username>"
    telegram = "<username>"
    # orcid = "<xxxx-xxxx-xxxx-xxxx>"
    email = "your-email@example.com"
    # gravatar = "your-email@example.com"
    # pgpkey = "<path-to-your-key-in-/static>"

[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 200
    url = "/portfolio/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
